### ISSUE TITLE
Add in :scm-url as a keyword to jar

### ISSUE THREAD

**Issue by kiranshila** [seancorfield/build-clj#1]
Cljdoc wants the url of the scm target to parse out articles, so this needs to get added into the POM. This is the `:url` key under `:scm` in `clojure.tools.build.api/write-pom`. A key like `:scm-url` in `(jar ..)` would be nice.

**Comment by seancorfield** [comment]
I'll have to give this some thought per my comments when I closed the PR. I'll keep this open as a reminder.

**Comment by seancorfield** [comment]
My solution here was to add a new `:scm` option to `jar` which should be a hash map with any elements you want/need. If you specify `:tag`, it will override `:scm {:tag "..."}` but otherwise you can just use `:scm` to specify `:url`, `:connection`, `:developerConnection`, and `:tag` if you want. This basically mimics `tools.build`'s approach.
